paths:
  original_images_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant-enumeration/xrays
  original_json_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant-enumeration/train_quadrant_enumeration.json
  s2_main_path: ..\Data\Processed\Stage 2 (Enumeration Detection)
  runs_s2_output: ..\Runs\Stage 2


model_args:
  data: ..\Data\Processed\Stage 2 (Enumeration Detection)\data.yaml