paths:
  original_images_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant/xrays
  original_json_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant/train_quadrant.json
  s1_main_path: ..\Data\Processed\Stage 1 (Quadrant Detection)
  runs_s1_output: ..\Runs\Stage 1

model_args:
  data: ..\Data\Processed\Stage 1 (Quadrant Detection)\data.yaml
  model: ../Models/yolo26s.pt
  epochs: 50
  save: True
  imgsz: 1024
  batch: 8
  patience: 10
  optimizer: AdamW
  lr0: 0.001
  lrf: 0.01
  plots: True
  verbose: True
  device: cuda
  workers: 4
  project: Runs
  name: Stage 1
  save_dir: ..\Runs\Stage 1
  auto_augment: None
  augment: False
  augment: True
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  cutmix: 0.0
  hsv_h: 0.015
  hsv_s: 0.4
  hsv_v: 0.4
  degrees: 5.0
  translate: 0.05
  scale: 0.1
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  erasing: 0.0