paths:
  original_images_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant-enumeration-disease/xrays
  original_json_path: ../Data/Raw/DENTEX CHALLENGE 2023/Training_data/quadrant-enumeration-disease/train_quadrant_enumeration_disease.json
  s2_cont_main_path: ../Data/Processed/Stage 2 Continued (Healthy & Disease Enumeration Detection)
  runs_s2_cont_output: ../Runs/Stage 2 Continued


model_args:
  data: ../Data/Processed/Stage 2 Continued (Healthy & Disease Enumeration Detection)/data.yaml
  model: ../Runs/Stage 2 Continued/weights/best.pt
  epochs: 50
  save: True
  imgsz: 1280
  batch: 8
  patience: 15
  optimizer: AdamW
  lr0: 0.0005
  lrf: 0.01
  plots: True
  verbose: True
  device: cuda
  workers: 4
  project: Runs
  name: Stage 2 Continued
  save_dir: ../Runs/Stage 2 Continued
  auto_augment: None
  augment: True
  mosaic: 0.0
  mixup: 0.0
  copy_paste: 0.0
  cutmix: 0.0
  hsv_h: 0.015
  hsv_s: 0.4
  hsv_v: 0.4
  degrees: 5.0
  translate: 0.05
  scale: 0.1
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.0
  erasing: 0.0